server:
  port: '8081'
  
spring:
  profiles:
   active: qa
  
---
spring:
  datasource:
    profile: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/school-dev
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello world, Welcome to Programming World

---
spring:
  datasource:
    profile: qa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/school-qa
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello world, Welcome to Programming World.
#Enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  datasource:
    profile: prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/school-prod
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Hello world, Welcome to Programming World
